### ISSUE TITLE
How to encode <start> <unknown> and <pad> words

### ISSUE THREAD

**Issue by rhaps0dy** [oxford-cs-deepnlp-2017/practical-3#2]
(I am an Oxford student taking this course, but I haven't found how to sign up to Piazza.)

I figure <pad> could be encoded with all zeros. Is it worth having separate dimensions for <start> and <pad> in the embeddings, such that all the words are embedded except those two which are one-hot? Otherwise, should they be random, learned, embeddings? Perhaps I can make only those two embeddings learnable.

Should I just implement all and test?

**Comment by bshillingford** [comment]
If you're learning all embeddings from scratch, treating <unk> etc. as
words (and hence having learned embeddings for them) is standard.

If all your inputs are one-hot vectors, that simply pushes the embeddings
as learned in the matrix above it, i.e. either way you're learning
embeddings anyway.

**Comment by rhaps0dy** [comment]
But what if I'm doing neither of those things (ie, my embeddings are not learned, and I'm not using one-hot input)? What if I'm using GloVe ?

Guess I'll add dimensions for `<unk>` and `<pad>`, and that will be like learning embeddings for them only.

**Comment by bshillingford** [comment]
If you're using pretrained embeddings then sure, adding an additional two
binary features is a reasonable way to do it.
